In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import os

In [2]:
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.mlp1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.mlp2 = nn.Linear(hidden_size, num_classes)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        out = self.mlp1(x)
        out = self.relu(out)
        out = self.mlp2(out)
        out = self.softmax(out)
        return out

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


In [5]:
input_size = 28*28*1 # MNIST 이미지 크기
hidden_size = 100
num_classes = 10 # 총 클래스 개수
model = NeuralNet(input_size, hidden_size, num_classes).to(device)
print(model)

NeuralNet(
  (mlp1): Linear(in_features=784, out_features=100, bias=True)
  (relu): ReLU()
  (mlp2): Linear(in_features=100, out_features=10, bias=True)
  (softmax): Softmax(dim=1)
)


In [6]:
data = torch.rand(1, 28*28).to(device)
print('data:',data.shape)

pred = model(data)
print('pred:',pred)

y_hat = pred.argmax(1)
print(y_hat)

data: torch.Size([1, 784])
pred: tensor([[0.1036, 0.1174, 0.1056, 0.1051, 0.0841, 0.1053, 0.0826, 0.0879, 0.0997,
         0.1087]], grad_fn=<SoftmaxBackward0>)
tensor([1])


In [7]:
pred.sum()

tensor(1., grad_fn=<SumBackward0>)

In [8]:
x = torch.randn(3, 28, 28)
x

tensor([[[ 0.5628, -1.9509, -1.2040,  ..., -0.4167, -0.8961, -0.9312],
         [ 0.2213, -1.6570, -0.1060,  ...,  0.1331, -1.6802, -0.1847],
         [ 0.3695,  2.0508, -0.2727,  ..., -1.8373, -0.3343, -1.7743],
         ...,
         [-0.0338,  0.9713,  0.1836,  ..., -1.3989,  1.3050,  0.2075],
         [ 0.7802, -0.5164,  0.6749,  ..., -0.4272,  0.9590,  0.9469],
         [-0.6150,  0.2238, -1.0838,  ..., -0.7383, -1.4740, -0.4260]],

        [[-0.7350, -0.1618,  1.0298,  ...,  2.3059, -2.2056,  0.9988],
         [-0.9880, -0.1160,  0.2779,  ...,  0.0669,  0.0667, -1.9656],
         [ 0.0296, -0.0485,  1.8013,  ...,  1.2469, -0.6278,  1.0681],
         ...,
         [-1.6991, -0.7992, -0.5076,  ..., -0.2147,  0.2684, -1.1654],
         [-0.6070,  1.4928, -1.3382,  ..., -1.7268, -0.6231, -0.6319],
         [-0.0803, -0.2175, -0.3891,  ..., -1.3543, -0.0812,  0.8255]],

        [[ 2.1894, -1.0788,  0.4165,  ..., -1.3191,  1.1884,  0.5310],
         [-0.2050,  0.7123, -0.5929,  ..., -0

In [9]:
fc_layer = nn.Linear(in_features=28*28, out_features=100)
x_after_fc = fc_layer(x.reshape(-1, 28*28))
print(x_after_fc.shape)

torch.Size([3, 100])


In [10]:
flatten = nn.Flatten()
flat_x = flatten(x)
flat_x.shape

torch.Size([3, 784])

In [12]:
fc_layer = nn.Linear(in_features=1*28*28, out_features=200)
x_after_fc = fc_layer(flat_x)
print(x_after_fc)

torch.Size([3, 200])

tensor([[ 7.8834e-02, -2.8208e-01, -1.8416e-01,  2.0586e-01,  4.3349e-01,
         -6.3971e-01, -4.4755e-01, -7.9621e-01, -4.6753e-01,  4.2442e-01,
          2.3321e-01,  9.3187e-02, -5.6064e-02,  3.9012e-01, -6.1363e-01,
         -7.3660e-01, -1.1514e+00,  2.2695e-02, -8.9200e-01,  9.8878e-01,
         -3.5091e-01,  2.4501e-01, -3.9910e-01, -8.4382e-01,  5.9782e-01,
         -7.5069e-01,  1.2278e+00, -7.7996e-02,  1.7950e-01, -4.0382e-01,
         -2.0233e-01,  1.9325e-01,  6.9677e-01,  1.1351e+00,  3.9608e-01,
         -3.6256e-01, -4.0165e-01,  3.4470e-01, -3.9680e-02,  6.9827e-01,
         -2.2079e-01, -5.4196e-01, -1.6981e-01,  1.3684e-01,  4.6476e-03,
          1.6004e-01,  5.0928e-01, -2.8371e-01, -6.1520e-01,  4.4792e-02,
          6.9076e-01, -8.8155e-03,  8.4843e-01,  1.2092e-01, -2.4637e-01,
         -3.9731e-01,  2.8272e-01,  8.1325e-01, -4.8994e-01, -5.2103e-01,
          3.5281e-02,  2.6610e-01, -7.7900e-01,  1.3782e+00, -4.2176e-01,
         -1.1525e+00, -3.2389e-01, -5.

torch.Size([3, 200])

In [13]:
x = torch.randn(3, 1, 28, 28)

In [15]:
before_relu = x[0][0][0]
print(before_relu)

tensor([ 0.8370,  1.7633, -0.0455,  0.1468, -0.4361, -0.5927, -0.1621, -0.9113,
         1.1931, -0.7825,  0.0450, -1.8752, -0.0771, -0.2857,  0.3110,  0.7255,
        -1.0788,  0.0679,  0.5458, -0.2774,  1.5507,  1.4614,  0.7979,  0.7218,
        -1.4168, -0.1721, -0.0814, -1.3554])


In [16]:
relu = nn.ReLU()
after_relu = relu(before_relu)
print(after_relu)

tensor([0.8370, 1.7633, 0.0000, 0.1468, 0.0000, 0.0000, 0.0000, 0.0000, 1.1931,
        0.0000, 0.0450, 0.0000, 0.0000, 0.0000, 0.3110, 0.7255, 0.0000, 0.0679,
        0.5458, 0.0000, 1.5507, 1.4614, 0.7979, 0.7218, 0.0000, 0.0000, 0.0000,
        0.0000])


In [17]:
x = torch.rand(1, 10)

In [18]:
softmax = nn.Softmax(dim=1)

In [19]:
pred = softmax(x)
pred

tensor([[0.1387, 0.1195, 0.0807, 0.0959, 0.0683, 0.1443, 0.1071, 0.0844, 0.0843,
         0.0768]])

In [20]:
pred.sum()

tensor(1.)

In [21]:
input_size = 28*28*1
hidden_size = 100
num_classes = 10

model = NeuralNet(input_size, hidden_size, num_classes).to(device)
print(model)

NeuralNet(
  (mlp1): Linear(in_features=784, out_features=100, bias=True)
  (relu): ReLU()
  (mlp2): Linear(in_features=100, out_features=10, bias=True)
  (softmax): Softmax(dim=1)
)


In [23]:
class NeuralNet2(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet2, self).__init__()
        
        self.sequential = nn.Sequential(
            nn.Linear(input_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, num_classes),
            nn.Softmax(dim=1)
        )

    def forward(self, x):
        out = self.sequential(x)
        return out

In [24]:
input_size = 28*28*1
hidden_size = 100
num_classes = 10

model = NeuralNet2(input_size, hidden_size, num_classes).to(device)
print(model)

NeuralNet2(
  (sequential): Sequential(
    (0): Linear(in_features=784, out_features=100, bias=True)
    (1): ReLU()
    (2): Linear(in_features=100, out_features=10, bias=True)
    (3): Softmax(dim=1)
  )
)
